Repository ProAlgos/ProAlgos-Cpp, pull requests merged in 2018-09, with the labels that each got.

#200 Remove "using namespaces std"
  C++/include/sorting/utils.hpp
  C++/test/algorithm/searching/binary_search.cpp
  C++/test/algorithm/searching/linear_search.cpp
  C++/test/algorithm/searching/ternary_search.cpp
Labels: Enhancement

#193 Added edit distance
  C++/CMakeLists.txt
  C++/README.md
  C++/include/algorithm/string/edit_distance.hpp
  C++/test/algorithm/string/edit_distance.cpp
Labels: Algorithm, String

#201 Migrate greatest common denominator algorithm
  C++/CMakeLists.txt
  C++/README.md
  C++/include/algorithm/number_theory/greatest_common_divisor.hpp
  C++/source/number_theory/gcd.cpp
  C++/test/algorithm/number_theory/greatest_common_divisor.cpp
Labels: Reorganise

#191 0-1 Knapsack
  C++/CMakeLists.txt
  C++/README.md
  C++/include/algorithm/dynamic_programming/0_1_knapsack.hpp
  C++/test/algorithm/dynamic_programming/0_1_knapsack.cpp
Labels: Algorithm, Dynamic programming

#202 Migrate extended Euclidean algorithm
  C++/CMakeLists.txt
  C++/README.md
  C++/include/algorithm/number_theory/extended_euclidean.hpp
  C++/source/number_theory/extended_euclid.cpp
  C++/test/algorithm/number_theory/extended_euclidean.cpp
Labels: Reorganise
